import './globals.css'
import { Inter,Aladin,Ubuntu } from '@next/font/google'
const inter=Inter({
  subsets:['latin'],
  weight:'400',
})
const aladin=Aladin({
  subsets:['latin'],
  weight:'400',
})
const ubuntu=Ubuntu({
  subsets:['latin'],
  weight:'400',
})


export const metadata = {
  title: 'Nutrition hackthon',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={ubuntu.className}>{children}</body>
    </html>
  )
}
